/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.projecttripper;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author rozan
 */
public class changepass extends javax.swing.JFrame {
    
    
    String user2 ;
    String user3;
//private Connection con;
  PreparedStatement ps;
  
  
  
   
    /**
     * Creates new form login
     */
    public changepass() {
        initComponents();
         setUser();
        setResizable(false);
         this.setLocationRelativeTo(null);
         this.hidePass.setVisible(false);
         this.hidePass1.setVisible(false);
         this.hidePass2.setVisible(false);
        
         
          System.out.println("user is"+user2);
          
         
         
          
         
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
     
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        viewPass = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        hidePass = new javax.swing.JLabel();
        viewPass1 = new javax.swing.JLabel();
        conPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        hidePass1 = new javax.swing.JLabel();
        hidePass2 = new javax.swing.JLabel();
        setUsername = new javax.swing.JLabel();
        viewPass2 = new javax.swing.JLabel();
        oldPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Change your password.....");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pass.png"))); // NOI18N
        jLabel3.setText("Old Password");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pass.png"))); // NOI18N
        jLabel4.setText("New Password");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        viewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eyeopen.png"))); // NOI18N
        viewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPassMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewPassMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                viewPassMouseReleased(evt);
            }
        });

        newPass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        newPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassActionPerformed(evt);
            }
        });
        newPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newPassKeyPressed(evt);
            }
        });

        hidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        hidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidePassMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePassMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hidePassMouseReleased(evt);
            }
        });

        viewPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eyeopen.png"))); // NOI18N
        viewPass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPass1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewPass1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                viewPass1MouseReleased(evt);
            }
        });

        conPass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        conPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        conPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conPassActionPerformed(evt);
            }
        });
        conPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                conPassKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pass.png"))); // NOI18N
        jLabel5.setText("Confirm Password");

        hidePass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        hidePass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidePass1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePass1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hidePass1MouseReleased(evt);
            }
        });

        hidePass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        hidePass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidePass2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePass2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hidePass2MouseReleased(evt);
            }
        });

        setUsername.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        setUsername.setForeground(new java.awt.Color(255, 51, 51));
        setUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        viewPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eyeopen.png"))); // NOI18N
        viewPass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPass2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewPass2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                viewPass2MouseReleased(evt);
            }
        });

        oldPass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        oldPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        oldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPassActionPerformed(evt);
            }
        });
        oldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oldPassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                        .addComponent(newPass)
                                        .addComponent(conPass, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(oldPass, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewPass)
                            .addComponent(viewPass1)
                            .addComponent(hidePass1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hidePass2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewPass2))
                            .addComponent(hidePass))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(viewPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hidePass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(hidePass1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewPass1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conPass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hidePass2)
                    .addComponent(viewPass2))
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
            String password=oldPass.getText().trim();
            String pass=newPass.getText().trim();
            String setPass=conPass.getText().trim();
            System.out.print("Enter 0");
 
        
            String query = "select username from Login where password=?  ";   
           try{
               
            ps= MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,password);
            ResultSet rs2 = ps.executeQuery();
            
            if (rs2.next())
            {
               
                    String user = rs2.getString("username");
                     System.out.print(user2);
                    
                     if(user2.equals(user))
                     {
                         ps.close();
                      
                        if(pass.equals(setPass))
                        {
                     
                         System.out.print("Enter 3");
                        String query1 = "update Login set password=? where password=? ";
                        ps= MyConnection.getConnection().prepareStatement(query1);
                        ps.setString(1,setPass);
                        ps.setString(2,password);
                        ps.executeUpdate();
                        ps.close();
                    
                        Component frame = null;
                        JOptionPane.showMessageDialog(frame,"Password Change Succefully." ,"Password Changed",JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    
                        }
                        else{
                         ps.close();
                         Component frame = null;
                        JOptionPane.showMessageDialog(frame,"Confirm  didnot match !!" ," Error.",JOptionPane.ERROR_MESSAGE); 
                        }
                     }
                     else{
                         ps.close();
                         Component frame = null;
                        JOptionPane.showMessageDialog(frame,"Old Password  didnot match !!" ," Error.",JOptionPane.ERROR_MESSAGE);
                     }
                     
                        
                 }
                 else{
                ps.close();
                 Component frame = null;
                JOptionPane.showMessageDialog(frame,"Old password  didnot match !!" ," Error.",JOptionPane.ERROR_MESSAGE);
                 }
                         
            
           }
    
            
        

        
        catch(Exception ex)
        {
            Logger.getLogger(PaymentDetails.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
            
        }
       
                                      

       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPassMouseClicked
                
            
       
    }//GEN-LAST:event_viewPassMouseClicked
      public  void setUser()
    {
              String query = "select userName from UserLogin where userId = 1";
         try {
             ps= MyConnection.getConnection().prepareStatement(query);
             ResultSet rs = ps.executeQuery();
             if (rs.next())
             {
                 String userName =  rs.getString("userName");
                 setUsername.setText(userName.toString());
                 System.out.println("username = "+  userName);
                 ps.close();
             }
             else
             {
                 ps.close();
                 System.out.println("Else of login:");
             }
         } catch (SQLException ex) {
             Logger.getLogger(ProjectTripper.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    private void newPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassActionPerformed

    private void viewPassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPassMouseReleased
        
    }//GEN-LAST:event_viewPassMouseReleased

    private void newPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPassKeyPressed
       
    }//GEN-LAST:event_newPassKeyPressed

    private void hidePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hidePassMouseClicked

    private void hidePassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_hidePassMouseReleased

    private void viewPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPassMousePressed
       hidePass.setVisible(true);
       viewPass.setVisible(false);
       oldPass.setEchoChar((char)0);
    }//GEN-LAST:event_viewPassMousePressed

    private void hidePassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMousePressed
      viewPass.setVisible(true);
       hidePass.setVisible(false);
       oldPass.setEchoChar('*');
    }//GEN-LAST:event_hidePassMousePressed

    private void viewPass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPass1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPass1MouseClicked

    private void viewPass1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPass1MousePressed
        hidePass1.setVisible(true);
       viewPass1.setVisible(false);
       newPass.setEchoChar((char)0);
    }//GEN-LAST:event_viewPass1MousePressed

    private void viewPass1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPass1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPass1MouseReleased

    private void conPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conPassActionPerformed

    private void conPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conPassKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_conPassKeyPressed

    private void hidePass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePass1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hidePass1MouseClicked

    private void hidePass1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePass1MousePressed
       viewPass1.setVisible(true);
       hidePass1.setVisible(false);
       newPass.setEchoChar('*');
    }//GEN-LAST:event_hidePass1MousePressed

    private void hidePass1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePass1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_hidePass1MouseReleased

    private void hidePass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePass2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hidePass2MouseClicked

    private void hidePass2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePass2MousePressed
      viewPass2.setVisible(true);
       hidePass2.setVisible(false);
       conPass.setEchoChar('*');
    }//GEN-LAST:event_hidePass2MousePressed

    private void hidePass2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePass2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_hidePass2MouseReleased

    private void viewPass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPass2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPass2MouseClicked

    private void viewPass2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPass2MousePressed
         hidePass2.setVisible(true);
        viewPass2.setVisible(false);
        conPass.setEchoChar((char)0);
    }//GEN-LAST:event_viewPass2MousePressed

    private void viewPass2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPass2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPass2MouseReleased

    private void oldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPassActionPerformed

    private void oldPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldPassKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPassKeyPressed

    /**
     * @param args the command line arguments
     *///<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField conPass;
    private javax.swing.JLabel hidePass;
    private javax.swing.JLabel hidePass1;
    private javax.swing.JLabel hidePass2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField oldPass;
    public javax.swing.JLabel setUsername;
    private javax.swing.JLabel viewPass;
    private javax.swing.JLabel viewPass1;
    private javax.swing.JLabel viewPass2;
    // End of variables declaration//GEN-END:variables
}
