/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.projecttripper;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rozan
 */


public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
  
    private Connection con;
    
    public String userName2;
    // private ArrayList<TripperValidation> list = new ArrayList();
    PreparedStatement ps;
    
    public login() {
        initComponents();
        setResizable(false);
         this.setLocationRelativeTo(null);
         this.hidePass.setVisible(false);
         
         this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
         
        
         this.addWindowListener(new WindowAdapter()
                 {
                   @Override
                   public void windowClosing(WindowEvent e){
                       
                       int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to close the system ?","EXIT", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
                       
                       if(x == JOptionPane.YES_OPTION)
                       {
                        e.getWindow().dispose();
                
                 }
                 else
                 {
                     System.out.print("working.....");
                 }
                       
                   }  
                 });
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        viewPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        hidePass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("WELCOME BACK,");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Sign in to continue ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/name.png"))); // NOI18N
        jLabel3.setText("Username:");

        txtUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pass.png"))); // NOI18N
        jLabel4.setText("Password:");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        viewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eyeopen.png"))); // NOI18N
        viewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPassMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewPassMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                viewPassMouseReleased(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });

        hidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        hidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidePassMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePassMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hidePassMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txtUser)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(txtPass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hidePass)
                            .addComponent(viewPass))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hidePass)
                            .addComponent(viewPass))))
                .addGap(57, 57, 57)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{
            // ps.close();
            String username=txtUser.getText().trim();
            String pass=txtPass.getText().trim();
            Class.forName("org.sqlite.JDBC");
            String url="jdbc:sqlite:Tripper.db";
            String query1 = "select username,password from Login where username=?";
            PreparedStatement ps;
            ps= MyConnection.getConnection().prepareStatement(query1);
            ps.setString(1,username);
            ResultSet rs2 = ps.executeQuery();
            if (rs2.next())
            {
                 String password = rs2.getString("password");
                 if (pass.equals(password))
                 {
                     userName2 = username;
                     
                     ps.close();
                     ProjectTripper obj = new ProjectTripper();
                   //  obj.user=userName2;
                    
                     try
                     {
                         System.out.println("Entered update");
                         int userId = 1;
                          String query2 = "update UserLogin set userName=? where userId=?";
                          ps = MyConnection.getConnection().prepareStatement(query2);
                          ps.setString(1,username);
                          ps.setInt(2,userId);
                          ps.executeUpdate();
                          ps.close();
                           obj.txtEnteredBy.setText(username);
                           obj.setVisible(true);
                           backup();
                           this.dispose();
                     }
                     catch (SQLException ex) {
                    Logger.getLogger(ProjectTripper.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    
                                   
                 }
                 else
                 {
                     ps.close();
                      Component frame = null;
                JOptionPane.showMessageDialog(frame,"Username or Password incorrect" ," Error.",JOptionPane.ERROR_MESSAGE);
                    
                 }
           
            
            }
            else
            {
                 ps.close();
                      Component frame = null;
                JOptionPane.showMessageDialog(frame,"Username or Password incorrect" ," Error.",JOptionPane.ERROR_MESSAGE);
            }
         }
        
        catch(Exception ex)
        {
            
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPassMouseClicked
                
            
       
    }//GEN-LAST:event_viewPassMouseClicked

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void viewPassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPassMouseReleased
        
    }//GEN-LAST:event_viewPassMouseReleased

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try{
            String username=txtUser.getText().trim();
            String pass=txtPass.getText().trim();
            Class.forName("org.sqlite.JDBC");
            String url="jdbc:sqlite:Tripper.db";
            String query1 = "select username,password from Login where username=?";
            PreparedStatement ps;
            ps= MyConnection.getConnection().prepareStatement(query1);
            ps.setString(1,username);
            ResultSet rs2 = ps.executeQuery();
            if (rs2.next())
            {
               
                 String password = rs2.getString("password");
                 if (pass.equals(password))
                 {
                     
                     ps.close();
                   ProjectTripper obj = new ProjectTripper();
                     obj.user=username;
                    
                     try
                     {
                         System.out.println("Entered update");
                         int userId = 1;
                          String query2 = "update UserLogin set userName=? where userId=?";
                          ps = MyConnection.getConnection().prepareStatement(query2);
                          ps.setString(1,username);
                          ps.setInt(2,userId);
                          ps.executeUpdate();
                          ps.close();
                           obj.txtEnteredBy.setText(username);
                            obj.setVisible(true);
                            backup();
                            this.dispose();
                                    
                     }
                     catch (SQLException ex) {
                    Logger.getLogger(ProjectTripper.class.getName()).log(Level.SEVERE, null, ex);
                     }

                     this.dispose();
                                   
                 }
                 else
                 {
                     ps.close();
                      Component frame = null;
                JOptionPane.showMessageDialog(frame,"Username or Password incorrect" ," Error.",JOptionPane.ERROR_MESSAGE);
                    
                 }
           
            
            }
         }
        
        catch(Exception ex)
        {
            
        }
        }
      
    }//GEN-LAST:event_txtPassKeyPressed
    public void backup()
      {
          File orginalFile = new File("Tripper.db");
          File newFile = new File ("C:\\Tripper\\Backup.db");
          
          
              try {
                  Files.copy(orginalFile.toPath(),newFile.toPath(),StandardCopyOption.REPLACE_EXISTING);
                  System.out.print("backup Creted");
              } catch (IOException ex) {
                  Logger.getLogger(ProjectTripper.class.getName()).log(Level.SEVERE, null, ex);
              }
          
      }
    private void hidePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hidePassMouseClicked

    private void hidePassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_hidePassMouseReleased

    private void viewPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPassMousePressed
       hidePass.setVisible(true);
       viewPass.setVisible(false);
       txtPass.setEchoChar((char)0);
    }//GEN-LAST:event_viewPassMousePressed

    private void hidePassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMousePressed
      viewPass.setVisible(true);
       hidePass.setVisible(false);
       txtPass.setEchoChar('*');
    }//GEN-LAST:event_hidePassMousePressed

    /**
     * @param args the command line arguments
     *///<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hidePass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel viewPass;
    // End of variables declaration//GEN-END:variables
}
