/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.projecttripper;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.DefaultTableCellRenderer;


/**
 *
 * @author BISHAL
 */
//private ArrayList<TripperValidation> list = new ArrayList();
public class ProjectTripper extends javax.swing.JFrame {
   
     public ArrayList<TripperValidation> list = new ArrayList();
    PreparedStatement ps;
    java.sql.Date date2;
   
    String user ;
    public ProjectTripper() {
        initComponents();
         setResizable(false);
         this.setLocationRelativeTo(null);
         addRow();
        setUser();
       
      
         this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
         
        
         this.addWindowListener(new WindowAdapter()
                 {
                   @Override
                   public void windowClosing(WindowEvent e){
                       
                       int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to close the system ?","EXIT", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
                       
                       if(x == JOptionPane.YES_OPTION)
                       {
                        e.getWindow().dispose();
                
                 }
                 else
                 {
                     System.out.print("working.....");
                 }
                       
                   }  
                 });
         
                  
         
         
         
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntry = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtKar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtOther = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDriver = new javax.swing.JTextField();
        txtDiselCost = new javax.swing.JTextField();
        txtRaw = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEnteredBy = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtRate = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTrip = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtOrder = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chooseDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtOrderNo = new javax.swing.JTextField();
        comboMaterial = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tripper Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1831, 829));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Entry Table", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI Symbol", 1, 24))); // NOI18N

        tblEntry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Order No.", "Ordered By", "Site Address", "Material ", "Trip", "Rate", "Income", "Disel Cost", "Raw Material", "Driver Vatta", "Pataka/kar", "Other Expenses", "Total Expenditure", "Entered By"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEntry.setGridColor(new java.awt.Color(0, 0, 0));
        tblEntry.setRowHeight(20);
        tblEntry.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblEntry.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblEntry.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblEntryPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblEntry);
        if (tblEntry.getColumnModel().getColumnCount() > 0) {
            tblEntry.getColumnModel().getColumn(0).setResizable(false);
            tblEntry.getColumnModel().getColumn(1).setResizable(false);
            tblEntry.getColumnModel().getColumn(2).setResizable(false);
            tblEntry.getColumnModel().getColumn(3).setResizable(false);
            tblEntry.getColumnModel().getColumn(4).setResizable(false);
            tblEntry.getColumnModel().getColumn(5).setResizable(false);
            tblEntry.getColumnModel().getColumn(6).setResizable(false);
            tblEntry.getColumnModel().getColumn(7).setResizable(false);
            tblEntry.getColumnModel().getColumn(8).setResizable(false);
            tblEntry.getColumnModel().getColumn(9).setResizable(false);
            tblEntry.getColumnModel().getColumn(10).setResizable(false);
            tblEntry.getColumnModel().getColumn(11).setResizable(false);
            tblEntry.getColumnModel().getColumn(12).setResizable(false);
            tblEntry.getColumnModel().getColumn(13).setResizable(false);
            tblEntry.getColumnModel().getColumn(14).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Expenditure", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        txtKar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel5.setText("Other Expenses:");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel1.setText("Disel Cost:");

        txtOther.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtherActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel4.setText("Pataka/Kar:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel2.setText("Raw Materials:");

        txtDriver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDriverActionPerformed(evt);
            }
        });

        txtDiselCost.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        txtRaw.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel3.setText("Driver Vatta:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel6.setText("Entered By:");

        txtEnteredBy.setEditable(false);
        txtEnteredBy.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel8.setText("Expenses Desc.:");

        txtDescription.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtOther, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(txtDriver)
                                    .addComponent(txtDiselCost)))
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRaw, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                        .addComponent(txtKar))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addGap(46, 46, 46)
                        .addComponent(txtEnteredBy, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtDiselCost, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRaw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(txtKar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnteredBy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Order Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        txtRate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel18.setText("Rate:");

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel17.setText("Trip:");

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel16.setText("Material:");

        txtTrip.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        txtAddress.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel15.setText("Site Address:");

        txtOrder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel14.setText("Ordered By:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel9.setText("Date :");

        chooseDate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel7.setText("Order No:");

        txtOrderNo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        comboMaterial.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        comboMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Misgitti", "Giti", "Baluwa", "Dunga", "Soling Dunga", "Base", "Mato", "Silicon" }));
        comboMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9))
                    .addComponent(jLabel15))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRate)
                    .addComponent(txtAddress)
                    .addComponent(chooseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMaterial, 0, 246, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel17)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7))
                        .addGap(43, 43, 43)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTrip, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(txtOrder)
                    .addComponent(txtOrderNo))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(chooseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtOrderNo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 0, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 0, 0));
        btnAdd.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jMenuBar1PropertyChange(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/presentation.png"))); // NOI18N
        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(10, 0, 10, 0));

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jMenuItem1.setText("New Entry");
        jMenuItem1.setMargin(new java.awt.Insets(0, 0, 10, 0));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jMenuItem2.setText("View Order");
        jMenuItem2.setMargin(new java.awt.Insets(0, 0, 10, 0));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/appointment.png"))); // NOI18N
        jMenuItem3.setText("View Order Details");
        jMenuItem3.setMargin(new java.awt.Insets(0, 0, 10, 0));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pos-terminal.png"))); // NOI18N
        jMenuItem4.setText("Record Payment");
        jMenuItem4.setMargin(new java.awt.Insets(0, 0, 10, 0));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vision.png"))); // NOI18N
        jMenuItem5.setText("View Credit");
        jMenuItem5.setMargin(new java.awt.Insets(0, 0, 10, 0));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        jMenuItem6.setText("Analysis Profit");
        jMenuItem6.setMargin(new java.awt.Insets(0, 0, 10, 0));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/review.png"))); // NOI18N
        jMenuItem8.setText("Change Password");
        jMenuItem8.setMargin(new java.awt.Insets(0, 0, 10, 0));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_2.png"))); // NOI18N
        jMenuItem7.setText("Logout");
        jMenuItem7.setMargin(new java.awt.Insets(0, 0, 10, 0));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDriverActionPerformed
   
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
 
        int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to close the system ?","EXIT", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
                       
                       if(x == JOptionPane.YES_OPTION)
                       {
                        this.dispose();
                
                 }
                 else
                 {
                     System.out.print("working.....");
                 }
        
         
    }//GEN-LAST:event_btnExitActionPerformed
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
            SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dFormat.format(chooseDate.getDate());
             DateTimeFormatter  formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate jDate1 = LocalDate.parse(date,formatter);
            date2 = java.sql.Date.valueOf(jDate1);
            int orderNo = Integer.parseInt(txtOrderNo.getText().trim());
            String orderBy = txtOrder.getText().trim();
            String siteAddress = txtAddress.getText().trim();
            String material = (String)comboMaterial.getSelectedItem();
            int trip = Integer.parseInt(txtTrip.getText().trim());
            double rate =Double.parseDouble(txtRate.getText().trim());
            double diselCost = Double.parseDouble(txtDiselCost.getText().trim());
            double rawMaterial = Double.parseDouble(txtRaw.getText().trim());
            double driverVatta =  Double.parseDouble(txtDriver.getText().trim());
            double kar =  Double.parseDouble(txtKar.getText().trim());
           // int otherExpenses = Integer.parseInt(txtOther.getText().trim());
            String description = txtDescription.getText().trim();
            String enteredBy = txtEnteredBy.getText().trim();
           
            double income = trip*rate;
            double totalExpenses = diselCost+rawMaterial+driverVatta+kar; 
            String query1 = "Select orderNo from Entry where orderNo = ?";
            if (date.equals("") || orderNo == 0 || orderBy.equals("") || siteAddress.equals("") || trip == 0 || diselCost < 0 || txtRaw.getText().equals("") || txtKar.getText().equals("")  )
            {
                 JOptionPane.showMessageDialog(null, "Please enter all textfields. some important text fields are empty.");
            }
            else
            {
                try {
            ps = MyConnection.getConnection().prepareStatement(query1);
             ps.setInt(1,orderNo);
            ResultSet rs = ps.executeQuery();
            System.out.println("Entered 06");
            if (rs.next())
            {
                JOptionPane.showMessageDialog(null, "Order id already exits.");
                 ps.close();
            }
            else
            {
                 ps.close();
            System.out.println("Entered 05");
                if (!txtOther.getText().equals(""))
                    {System.out.println("Entered 04");
                        if(!description.equals(""))
                        {   System.out.println("Entered 03");
                            System.out.println("Entered 02");
                            int otherExpenses = Integer.parseInt(txtOther.getText().trim());
                                    PreparedStatement stmt;
                                    String query = "insert into Entry values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                                    stmt = MyConnection.getConnection().prepareStatement(query);
                                    stmt.setDate(1,date2);
                                    stmt.setInt(2,orderNo);
                                    stmt.setString(3,orderBy);
                                     stmt.setString(4,siteAddress);
                                     stmt.setString(5,material);
                                     stmt.setInt(6,trip);
                                     stmt.setDouble(7,rate);
                                     stmt.setDouble(8,income);
                                     stmt.setDouble(9,diselCost);
                                     stmt.setDouble(10,rawMaterial);
                                     stmt.setDouble(11,driverVatta);
                                     stmt.setDouble(12,kar);
                                     stmt.setDouble(13,otherExpenses);
                                     stmt.setDouble(14,totalExpenses);
                                     stmt.setString(15,description);
                                     stmt.setString(16,enteredBy);
                                     stmt.executeUpdate();
                                     stmt.close();
                                     enterCredit();
                            DefaultTableModel model = (DefaultTableModel)tblEntry.getModel();
                            model.addRow (new Object[]{date,orderNo, orderBy, siteAddress, material,trip, rate, income, diselCost,rawMaterial,driverVatta,kar,otherExpenses,totalExpenses,enteredBy});
                        }  
                        else
                        {
                             JOptionPane.showMessageDialog(null, "Please fill some discription"); 
                        }
                    }
                else
                {
                    System.out.println("Entered 01");
                    
                             PreparedStatement stmt;
                                    String query = "insert into Entry(orderDate,orderNo, orderBy, siteAddress, material,trip, rate, price, diselCost,materialCost,driverVatta,pattakakar,totalExpenses,enteredBy) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                                    stmt = MyConnection.getConnection().prepareStatement(query);
                                    stmt.setDate(1,date2);
                                    stmt.setInt(2,orderNo);
                                    stmt.setString(3,orderBy);
                                     stmt.setString(4,siteAddress);
                                     stmt.setString(5,material);
                                     stmt.setInt(6,trip);
                                     stmt.setDouble(7,rate);
                                     stmt.setDouble(8,income);
                                     stmt.setDouble(9,diselCost);
                                     stmt.setDouble(10,rawMaterial);
                                     stmt.setDouble(11,driverVatta);
                                     stmt.setDouble(12,kar);
                                     stmt.setDouble(13,totalExpenses);
                                     stmt.setString(14,enteredBy);
                                     stmt.executeUpdate();
                                     stmt.close();
                                     enterCredit();
                                     DefaultTableModel model = (DefaultTableModel)tblEntry.getModel();
                                    model.addRow (new Object[]{date,orderNo, orderBy, siteAddress, material,trip, rate, income, diselCost,rawMaterial,driverVatta,kar,0,totalExpenses,enteredBy});
                }
                
        }
        }
        
        catch (SQLException ex) {
            Logger.getLogger(ProjectTripper.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (NumberFormatException ex)
        {
            if (txtOther.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please fill some Other Expenses either with value or Zero"); 
            }
        }
            }
        
        }
        
        catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Please fill all the required fields."); 
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Please check all the data and enter correct data."); 
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

     public void addRow()
    {
        DefaultTableModel model = (DefaultTableModel)tblEntry.getModel();
        model.setRowCount(0);
        LocalDate today = LocalDate.now(); 
        LocalDate pastDate = today.plusDays(-15);
         DateTimeFormatter  formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
         java.sql.Date date3 = java.sql.Date.valueOf(pastDate);
         System.out.println("username is :"+ user);
         String query =  "select*from Entry where orderDate > ?";
        try {
            System.out.println("Entered 001");
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setDate(1, date3);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                System.out.println("Entered 002");
                 
                 model.addRow (new Object[]{rs.getDate("orderDate"),rs.getString("orderNo"), rs.getString("orderBy"), rs.getString("siteAddress"), rs.getString("material"),rs.getInt("trip"), rs.getDouble("rate"), rs.getDouble("price"), rs.getDouble("diselCost"),rs.getDouble("diselCost"),rs.getDouble("driverVatta"),rs.getDouble("pattakaKar"),rs.getDouble("otherExpenses"),rs.getDouble("totalExpenses"),rs.getString("enteredBy")});
            }
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(ProjectTripper.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
      public  void setUser()
    {
              String query = "select userName from UserLogin where userId = 1";
         try {
             ps= MyConnection.getConnection().prepareStatement(query);
             ResultSet rs = ps.executeQuery();
             if (rs.next())
             {
                 user = rs.getString("userName");
                 txtEnteredBy.setText(rs.getString("userName"));
                 ps.close();
             }
             else
             {
                 ps.close();
             }
         } catch (SQLException ex) {
             Logger.getLogger(ProjectTripper.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
      
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
            chooseDate.setCalendar(null);
             txtOrder.setText(null);
             txtAddress.setText(null);
             txtOrderNo.setText(null);
             txtDescription.setText(null);
             txtTrip.setText(null);
             txtRate.setText(null);
             txtDiselCost.setText(null);
             txtRaw.setText(null);
             txtDriver.setText(null);
             txtKar.setText(null);
             txtOther.setText(null);
             //txtContent.setText(null);
             //txtReceived.setText(null);
             //txtGiven.setText(null);
             //txtBy.setText(null);
             
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtherActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       
       JFrame f= new JFrame();
       String delete = JOptionPane.showInputDialog(f,"Enter Order No of the Entry You want to Delete ", "Delete Entry", JOptionPane.INFORMATION_MESSAGE); 
       String deleteEntry = delete.trim();
       try
       {
            try
                   {
                    String compare = "Select orderNo from Entry where orderNo = ?";
                    ps = MyConnection.getConnection().prepareStatement(compare);
                    ps.setString(1,delete);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next())
                    {
                        String compareTo = rs.getString("orderNo");
                        if(deleteEntry.equals(compareTo))
                        {    ps.close();
                             PreparedStatement ps2;
                             String query = "Delete from Entry where orderNo = ?";
                             ps2 = MyConnection.getConnection().prepareStatement(query);
                             ps2.setString(1,deleteEntry);
                             ps2.executeUpdate();
                             ps2.close();
                             JOptionPane.showMessageDialog(null, "Entry Deleted");
                               
                            for (int i=0; i<tblEntry.getRowCount(); i++)
                             {
                                 
                                if(tblEntry.getValueAt(i,1).equals(deleteEntry))
                                {   
                                
                                    DefaultTableModel model = (DefaultTableModel)tblEntry.getModel();
                                    model.removeRow(i);
                                    System.out.print(i);
                                    break;
                                }
                           
                            
                            }
                             try
                             {
                                 String query2 = "Delete from credit where orderId = ?";
                                 ps=MyConnection.getConnection().prepareStatement(query2);
                                 ps.setString(1,deleteEntry);
                                 ps.executeUpdate();
                                 ps.close();
                             }
                              catch(SQLException e)
                            {
                              e.printStackTrace(); 
                              JOptionPane.showMessageDialog(null, "Sorry, Please Contact Developers");
                            }
                             
                           
                             
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Sorry, No data found");
                        }
                        
                    }
                      else
                        {
                            JOptionPane.showMessageDialog(null, "Sorry, No data found");
                        }
                    
                    
                    
                   }
                   catch(SQLException e)
                   {
                     e.printStackTrace(); 
                     JOptionPane.showMessageDialog(null, "Sorry, Please Contact Developers");
                   }
                     
           //JOptionPane.showMessageDialog(null, "Entry Deleted");
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, "Sorry, No data found");
           System.out.println("Entered 01");
       }
       
    }//GEN-LAST:event_btnDeleteActionPerformed
    public void enterCredit()
    {
        String orderNo = txtOrderNo.getText().trim();
        String orderBy = txtOrder.getText().trim();
        int trip = Integer.parseInt(txtTrip.getText().trim());
        double rate =Double.parseDouble(txtRate.getText().trim());
        double income = trip*rate;
        double paidAmount = 0;
        
        String query = "insert into Credit(orderDate,orderId,orderBy,totalAmount,paidAmount,dueAmount) values(?,?,?,?,?,?)";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setDate(1,date2);
            ps.setString(2,orderNo);
            ps.setString(3,orderBy);
            ps.setDouble(4,income);
            ps.setDouble(5,paidAmount);
            ps.setDouble(6,income);
            ps.executeUpdate();
            ps.close();
            JOptionPane.showMessageDialog(null, "Successfully Inserted");
        } catch (SQLException ex) {
            Logger.getLogger(ProjectTripper.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
        
    }
    private void tblEntryPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblEntryPropertyChange
        JTableHeader Theader = tblEntry.getTableHeader();
        Theader.setBackground(new Color(255,0,0));
        Theader.setForeground(Color.white);
        Theader.setFont(new Font("Tahoma", Font.PLAIN, 18));
        
    }//GEN-LAST:event_tblEntryPropertyChange
    
    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ProjectTripper obj = new ProjectTripper();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        OderDetails obj = new OderDetails();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        View obj = new View();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        PaymentDetails obj = new PaymentDetails();
        obj.setVisible(true);
        obj.tbpPayment.setSelectedIndex(1);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        PaymentDetails obj = new PaymentDetails();
        obj.setVisible(true);
        obj.tbpPayment.setSelectedIndex(0);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        PaymentDetails obj = new PaymentDetails();
        obj.setVisible(true);
        obj.tbpPayment.setSelectedIndex(2);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        int p = JOptionPane.showConfirmDialog(null,"Do you want to Logout?","Logout",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(p==0)
        {
            login obj = new login();
            obj.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuBar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jMenuBar1PropertyChange

    }//GEN-LAST:event_jMenuBar1PropertyChange

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        changepass obj = new changepass();
        obj.setVisible(true);
        obj.user2 = user;
        //sobj.setUsername.setText(user);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void comboMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectTripper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectTripper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectTripper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectTripper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectTripper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private com.toedter.calendar.JDateChooser chooseDate;
    private javax.swing.JComboBox<String> comboMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEntry;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtDiselCost;
    private javax.swing.JTextField txtDriver;
    public javax.swing.JTextField txtEnteredBy;
    private javax.swing.JTextField txtKar;
    private javax.swing.JTextField txtOrder;
    private javax.swing.JTextField txtOrderNo;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtRaw;
    private javax.swing.JTextField txtTrip;
    // End of variables declaration//GEN-END:variables
}

